### ISSUE TITLE
Cannot Find Gamemode File

### ISSUE THREAD

**Issue by PixelGM** [federicodangelo/CubeWorld#4]
I cannot find the file for game mode names eg: basic w/ enemies, I would like to modify the names so any help would be greatly appreciated :)

I cannot find the file for names like below
![image](https://user-images.githubusercontent.com/40614688/71578060-50b38680-2b42-11ea-9382-fffeb1213283.png)

**Comment by federicodangelo** [comment]
They are located in https://github.com/federicodangelo/CubeWorld/tree/master/CubeWorldLibrary/CubeWorld/Gameplay
The game's main logic is in it's own Visual Studio project.. the idea was to have the game logic run without any Unity3D dependency, so a server could be built without unsing Unity3D... that's why it's on a different project :)

**Comment by PixelGM** [comment]
Thankyou so much
